---
- include_vars: main.yml

- name: Set up users
  include: user.yml

- name: Copy keys
  include: keys.yml

- name: Set locale
  include: locale.yml

- name: Install packages
  include: packages.yml

- name: Install configuration
  include: config.yml